spring:
  application:
    name: userservice

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      #      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #  data:
  #    redis:
  #      host: localhost
  #      port: 6379
  #      # password: yourpassword  # ??? ??
  #      timeout: 60000

  logging:
    level:
      root: INFO
      com.c202.userservice: DEBUG
      org.springframework.security: DEBUG
      org.springframework.data.redis: DEBUG

jwt:
  secret-key: yourVerySecretKeyHereItShouldBeAtLeast32CharactersLong
  access-token-validity-in-ms: 3600000
  refresh-token-validity-in-ms: 2592000000
  token-prefix: Bearer
  header-string: Authorization

